# -*- coding: utf-8 -*-
"""VisionaryText.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUIBL4Ze7ekjvVdh4b_mspxPwIqqys0P
"""

# Install required packages (run this cell first)
!pip install diffusers transformers accelerate gradio torch --quiet

# Import libraries
from diffusers import StableDiffusionPipeline
import torch
import gradio as gr

# Load pre-trained Stable Diffusion model
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
)
pipe = pipe.to("cpu")

# Define the image generation function
def generate_image(prompt, style):
    prompt_with_style = f"{prompt}, {style}"
    image = pipe(prompt_with_style).images[0]
    return image

# Create a Gradio interface
interface = gr.Interface(
    fn=generate_image,
    inputs=[
        gr.Textbox(label="Enter your prompt"),
        gr.Dropdown(["photorealistic", "anime", "digital art"], label="Style")
    ],
    outputs=gr.Image(type="pil"),
    title="VisionaryText: AI Text-to-Image Generator",
    description="Enter a prompt and select a style to generate AI-powered images instantly!"
)

# Launch the interactive demo
interface.launch()